#ifndef FILEANDSYSTEM_GLOBAL_H
#define FILEANDSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEANDSYSTEM_LIBRARY)
#  define FILEANDSYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEANDSYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEANDSYSTEM_GLOBAL_H
