#ifndef SUSPENDEDTIPBAR_GLOBAL_H
#define SUSPENDEDTIPBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SUSPENDEDTIPBAR_LIBRARY)
#  define SUSPENDEDTIPBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SUSPENDEDTIPBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SUSPENDEDTIPBAR_GLOBAL_H
